"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

from utils.setting_utils import filter_no_traceback

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-build-time-fallback-key")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.redirects",
    # rest framework
    "rest_framework",
    "django_filters",
    # "rest_framework_simplejwt",
    # "rest_framework_simplejwt.token_blacklist",
    # django-allauth
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # apps
    "cosmetics_shop.apps.CosmeticsShopConfig",
    "staff.apps.StaffConfig",
    "accounts.apps.AccountsConfig",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.redirects.middleware.RedirectFallbackMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cosmetics_shop.context_processors.cart_item_count",
                "cosmetics_shop.context_processors.register_form",
                "cosmetics_shop.context_processors.is_pending_deletion_client",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"
TIME_ZONE = "Europe/Kyiv"

USE_I18N = True
USE_L10N = True

LANGUAGES = [
    ("ru", "Русский"),
]

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", BASE_DIR.parent / "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR.parent / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

AUTH_USER_MODEL = "accounts.CustomUser"

DEFAULT_STAFF_GROUP_NAME = "Гости"

SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
ACCOUNT_PREVENT_ENUMERATION = False

# Headless Setup
HEADLESS_FRONTEND_URLS = {
    "account_login": "/accounts/login/",
}
ALLAUTH_HEADLESS_ONLY = False


AUTHENTICATION_BACKENDS = [
    "accounts.authentication.EmailAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("CLIENT_ID"),
            "secret": os.getenv("CLIENT_SECRET"),
            "key": "",
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True


SITE_URL = "http://127.0.0.1:8000"
DEFAULT_FROM_EMAIL = "Cosmetics Shop <noreply@gmail.com>"


PRODUCTS_PER_PAGE = 20


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://*.ngrok-free.app",
]

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# NOVA POSHTA
NOVA_POSHTA_API_URL = "https://api.novaposhta.ua/v2.0/json/"
NOVA_POSHTA_API_KEY = os.getenv("NOVA_POSHTA_API_KEY")

# MONOBANK
MONO_URL_STATUS = "https://api.monobank.ua/api/merchant/invoice/status"
MONO_URL = "https://api.monobank.ua/api/merchant/invoice/create"
MONO_TOKEN = os.getenv("MONO_TOKEN")


REDIS_URL = os.getenv("REDIS_URL") or os.getenv("REDISCLOUD_URL")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# CELERY SETTINGS
CELERY_BEAT_SCHEDULE = {
    "check-completed-orders-for-deletion": {
        "task": "accounts.tasks.update_pending_deletion_dates",
        "schedule": crontab(minute=0),  # start every hour
    },
    "anonymize-clients-every-night": {
        "task": "accounts.tasks.process_client_anonymization",
        "schedule": crontab(minute=0, hour=3),  # 03:00
    },
    "cleanup-orders-every-15-minutes": {
        "task": "cosmetics_shop.tasks.cleanup_expired_orders",
        "schedule": crontab(minute="*/15"),  # каждые 15 минут
    },
}
CELERY_TIMEZONE = "Europe/Kiev"
CELERY_ENABLE_UTC = True

CELERY_BROKER_URL = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"


ON_HEROKU = os.getenv("DYNO") is not None

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "no_traceback": {
            "()": "django.utils.log.CallbackFilter",
            "callback": filter_no_traceback,
        },
    },
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
        },
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(process)d] [%(name)s:%(lineno)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        **(
            {}
            if ON_HEROKU
            else {
                "file": {
                    "class": "logging.handlers.RotatingFileHandler",
                    "filename": BASE_DIR.parent / "logs/django.log",
                    "maxBytes": 1024 * 1024 * 10,
                    "backupCount": 5,
                    "formatter": "verbose",
                    "filters": ["no_traceback"],
                },
                "errors_file": {
                    "class": "logging.handlers.RotatingFileHandler",
                    "filename": BASE_DIR.parent / "logs/errors.log",
                    "maxBytes": 1024 * 1024 * 10,
                    "backupCount": 5,
                    "level": "ERROR",
                    "formatter": "verbose",
                    "filters": ["no_traceback"],
                },
            }
        ),
    },
}

DEFAULT_HANDLERS = ["console"] if ON_HEROKU else ["console", "file", "errors_file"]

LOGGING["loggers"] = {
    "django": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": True,
    },
    "celery": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": False,
    },
    "cosmetics_shop": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": False,
    },
    "accounts": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": False,
    },
    "staff": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": False,
    },
    "api": {
        "handlers": DEFAULT_HANDLERS,
        "level": "INFO",
        "propagate": False,
    },
}


REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "login": "5/min",
        "register": "3/min",
        "order_create": "10/hour",
    },
}

PRODUCTS_FILE = BASE_DIR.parent / "data" / "products_data.json"
