# Generated by Django 5.2.1 on 2026-01-24 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_customuser_permissions_customuser_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activationtoken",
            options={
                "verbose_name": "Токен активации",
                "verbose_name_plural": "Токены активации",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
