# Generated by Django 5.2.1 on 2026-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_activationtoken_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activationtoken",
            options={
                "verbose_name": "токен активации",
                "verbose_name_plural": "Токены активации",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
