# Generated by Django 5.2.1 on 2026-02-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_activationtoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deletion_scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_pending_deletion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
