# Generated by Django 5.2.1 on 2026-03-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_deletion_scheduled_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="deletion_scheduled_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_pending_deletion",
        ),
    ]
