# Generated by Django 5.2.1 on 2026-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0001_initial_squashed_0009_remove_customuser_deletion_scheduled_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
