# Generated by Django 5.2.1 on 2026-04-05 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activationtoken",
            name="user",
        ),
        migrations.AddField(
            model_name="activationtoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activationtoken",
            name="email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Email для приглашения"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activationtoken",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
