# Generated by Django 5.2.1 on 2026-04-01 17:24

import accounts.utils.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("cosmetics_shop", "0001_initial"),
        ("cosmetics_shop", "0002_brand_product_product_code_product_slug_and_more"),
        ("cosmetics_shop", "0003_rename_name_brand_brand_name_and_more"),
        ("cosmetics_shop", "0004_rename_card_cart_rename_carditem_cartitem_and_more"),
        ("cosmetics_shop", "0005_remove_order_user_order_snapshot_address_and_more"),
        ("cosmetics_shop", "0006_alter_cart_user"),
        ("cosmetics_shop", "0007_product_stock_orderstatuslog"),
        ("cosmetics_shop", "0008_remove_order_status_order_code_product_code_and_more"),
        ("cosmetics_shop", "0009_remove_product_slug_alter_order_code_and_more"),
        ("cosmetics_shop", "0010_alter_orderitem_product"),
        ("cosmetics_shop", "0011_tag_alter_order_options_product_tags_favorite"),
        (
            "cosmetics_shop",
            "0012_orderitem_snapshot_price_orderitem_snapshot_product_and_more",
        ),
        ("cosmetics_shop", "0013_alter_brand_options"),
        ("cosmetics_shop", "0014_remove_client_full_name_client_first_name_and_more"),
        ("cosmetics_shop", "0015_remove_client_email_remove_order_snapshot_email"),
        ("cosmetics_shop", "0016_alter_category_options_alter_order_options_and_more"),
        ("cosmetics_shop", "0017_alter_category_options_alter_order_options_and_more"),
        ("cosmetics_shop", "0018_alter_brand_options_alter_category_options_and_more"),
        ("cosmetics_shop", "0019_alter_client_options_alter_deliveryaddress_options"),
        ("cosmetics_shop", "0020_alter_product_options"),
        ("cosmetics_shop", "0021_alter_brand_options_alter_category_options_and_more"),
        (
            "cosmetics_shop",
            "0022_alter_category_options_alter_groupproduct_options_and_more",
        ),
        ("cosmetics_shop", "0023_remove_deliveryaddress_is_primary_and_more"),
        ("cosmetics_shop", "0024_rename_is_main_deliveryaddress_is_primary_and_more"),
        ("cosmetics_shop", "0025_alter_cart_options_alter_favorite_options_and_more"),
        ("cosmetics_shop", "0026_client_deletion_scheduled_date_and_more"),
        ("cosmetics_shop", "0027_order_completed_at"),
        ("cosmetics_shop", "0028_alter_orderstatuslog_options_and_more"),
        ("cosmetics_shop", "0029_payment"),
        ("cosmetics_shop", "0030_tag_slug_alter_order_status_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "категорию",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.category",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "группу товаров",
                "verbose_name_plural": "Группы товаров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=10,
                        validators=[accounts.utils.validators.validate_phone_number],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "клиента",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("post_office", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="cosmetics_shop.client",
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "адрес доставки",
                "verbose_name_plural": "Адреса доставки",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("snapshot_address", models.TextField(default="")),
                ("snapshot_name", models.CharField(max_length=200)),
                ("snapshot_phone", models.CharField(default="", max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cosmetics_shop.client",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("snapshot_email", models.EmailField(default="", max_length=254)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Payment received"),
                            (2, "Payment failed"),
                            (3, "In progress"),
                            (4, "Completed"),
                            (5, "Closed"),
                            (6, "Canceled"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.brand",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.groupproduct",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "code",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/image.jpg", upload_to="product_images/"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="cosmetics_shop.tag"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "Товары",
                "permissions": [
                    ("can_change_product_price", "Может изменять цену товара"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Payment received"),
                            (2, "Payment failed"),
                            (3, "In progress"),
                            (4, "Completed"),
                            (5, "Closed"),
                            (6, "Canceled"),
                        ],
                        default=0,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_log",
                        to="cosmetics_shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "статус заказа",
                "verbose_name_plural": "Статусы заказов",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cosmetics_shop.product",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена на момент покупки",
                        max_digits=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="cosmetics_shop.order",
                    ),
                ),
                ("snapshot_product", models.CharField(default="", max_length=100)),
            ],
            options={
                "verbose_name": "товар в заказе",
                "verbose_name_plural": "товары в заказе",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosmetics_shop.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "product")},
            },
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("email",),
                name="unique_registered_email",
            ),
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="client",
            name="unique_registered_email",
        ),
        migrations.AddField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="cosmetics_shop.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Контактный email клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                max_length=13,
                validators=[accounts.utils.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="cosmetics_shop.product",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="cosmetics_shop.client",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_status_log",
                to="cosmetics_shop.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cosmetics_shop.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cosmetics_shop.groupproduct",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="deletion_scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_pending_deletion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Новый"),
                    (1, "Успешная оплата"),
                    (2, "Оплата не прошла"),
                    (3, "Доставляется"),
                    (4, "Получен"),
                    (5, "Отменен"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "New"),
                    (1, "Payment received"),
                    (2, "Payment failed"),
                    (3, "In progress"),
                    (4, "Completed"),
                    (5, "Canceled"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "ordering": ["-changed_at", "-id"],
                "verbose_name": "статус заказа",
                "verbose_name_plural": "Статусы заказов",
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="snapshot_product",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card (Online)"),
                            ("cash", "Cash on delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cosmetics_shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Новый"),
                    (1, "Успешная оплата"),
                    (2, "Оплата не прошла"),
                    (3, "Доставляется"),
                    (4, "Получен"),
                    (5, "Отменен"),
                ],
                default=0,
            ),
        ),
    ]
