# Generated by Django 5.2.1 on 2025-06-16 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics_shop', '0003_rename_name_brand_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='cart',
        ),
    ]
