# Generated by Django 5.2.1 on 2025-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0008_remove_order_status_order_code_product_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
