# Generated by Django 5.2.1 on 2025-07-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0009_remove_product_slug_alter_order_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cosmetics_shop.product",
            ),
        ),
    ]
