# Generated by Django 5.2.1 on 2025-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0011_tag_alter_order_options_product_tags_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_product",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="groupproduct",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
