# Generated by Django 5.2.1 on 2025-10-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cosmetics_shop",
            "0012_orderitem_snapshot_price_orderitem_snapshot_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name"]},
        ),
    ]
