# Generated by Django 5.2.1 on 2025-10-20 20:43

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0013_alter_brand_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="full_name",
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[accounts.utils.validators.validate_phone_number],
            ),
        ),
    ]
