# Generated by Django 5.2.1 on 2025-10-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0014_remove_client_full_name_client_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="snapshot_email",
        ),
    ]
