# Generated by Django 5.2.1 on 2026-01-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0015_remove_client_email_remove_order_snapshot_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    ("can_manage_categories", "Может управлять категориями")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-id"],
                "permissions": [
                    ("can_view_all_orders", "Может просматривать все заказы"),
                    ("can_delete_orders", "Может удалять заказы"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "ordering": ["-changed_at"],
                "permissions": [
                    ("can_change_order_status", "Может изменить статус заказа")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_edit_product", "Может изменять товар"),
                    ("can_delete_product", "Может удалить товар"),
                    ("can_add_product", "Может добавлять товар"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                ]
            },
        ),
    ]
