# Generated by Django 5.2.1 on 2026-01-14 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0016_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={"ordering": ["-changed_at"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
