# Generated by Django 5.2.1 on 2026-01-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0017_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="groupproduct",
            options={
                "verbose_name": "Группа товаров",
                "verbose_name_plural": "Группы товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-id"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Статус заказа",
                "verbose_name_plural": "Статусы заказов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
    ]
