# Generated by Django 5.2.1 on 2026-01-24 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0018_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={
                "verbose_name": "Адрес доставки",
                "verbose_name_plural": "Адреса доставки",
            },
        ),
    ]
