# Generated by Django 5.2.1 on 2026-01-29 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0019_alter_client_options_alter_deliveryaddress_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_change_product_price", "Может изменять цену товара"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
