# Generated by Django 5.2.1 on 2026-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0020_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категорию", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "клиента", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={
                "verbose_name": "адрес доставки",
                "verbose_name_plural": "Адреса доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="groupproduct",
            options={
                "verbose_name": "группу товаров",
                "verbose_name_plural": "Группы товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-id"],
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "товар в заказе",
                "verbose_name_plural": "товары в заказе",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "статус заказа",
                "verbose_name_plural": "Статусы заказов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_change_product_price", "Может изменять цену товара"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тег", "verbose_name_plural": "Теги"},
        ),
    ]
