# Generated by Django 5.2.1 on 2026-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0021_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "категорию",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="groupproduct",
            options={
                "ordering": ["name"],
                "verbose_name": "группу товаров",
                "verbose_name_plural": "Группы товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupproduct",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="snapshot_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="snapshot_name",
            field=models.CharField(max_length=200),
        ),
    ]
