# Generated by Django 5.2.1 on 2026-02-17 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cosmetics_shop",
            "0022_alter_category_options_alter_groupproduct_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="snapshot_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="snapshot_quantity",
        ),
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "New"),
                    (1, "Payment received"),
                    (2, "Payment failed"),
                    (3, "In progress"),
                    (4, "Completed"),
                    (5, "Closed"),
                    (6, "Canceled"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="cosmetics_shop.client",
            ),
        ),
        migrations.AlterField(
            model_name="groupproduct",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="cosmetics_shop.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена на момент покупки", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
