# Generated by Django 5.2.1 on 2026-02-18 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0023_remove_deliveryaddress_is_primary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryaddress",
            old_name="is_main",
            new_name="is_primary",
        ),
        migrations.RemoveField(
            model_name="client",
            name="was_registered",
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("email",),
                name="unique_registered_email",
            ),
        ),
    ]
