# Generated by Django 5.2.1 on 2026-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0025_alter_cart_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deletion_scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_pending_deletion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "New"),
                    (1, "Payment received"),
                    (2, "Payment failed"),
                    (3, "In progress"),
                    (4, "Completed"),
                    (5, "Canceled"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "New"),
                    (1, "Payment received"),
                    (2, "Payment failed"),
                    (3, "In progress"),
                    (4, "Completed"),
                    (5, "Canceled"),
                ],
                default=0,
            ),
        ),
    ]
