# Generated by Django 5.2.1 on 2026-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics_shop", "0026_client_deletion_scheduled_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
