# Generated by Django 5.2.1 on 2026-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics_shop', '0027_order_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-changed_at', '-id'], 'verbose_name': 'статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_product',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
