# Generated by Django 5.2.1 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics_shop", "0029_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Новый"),
                    (1, "Успешная оплата"),
                    (2, "Оплата не прошла"),
                    (3, "Доставляется"),
                    (4, "Получен"),
                    (5, "Отменен"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Новый"),
                    (1, "Успешная оплата"),
                    (2, "Оплата не прошла"),
                    (3, "Доставляется"),
                    (4, "Получен"),
                    (5, "Отменен"),
                ],
                default=0,
            ),
        ),
    ]
