# Generated by Django 5.2.1 on 2026-04-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cosmetics_shop",
            "0001_initial_squashed_0030_tag_slug_alter_order_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="street",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="cosmetics_shop.cart",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="snapshot_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="snapshot_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="snapshot_phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, unique=True
            ),
        ),
    ]
