# Generated by Django 5.2.1 on 2026-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("staff", "0001_initial"),
        ("staff", "0002_alter_staffpermission_options"),
        ("staff", "0003_alter_staffpermission_options"),
        ("staff", "0004_alter_staffpermission_options"),
        ("staff", "0005_alter_staffpermission_options"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("dashboard_view", "Может просматривать статистику"),
                    ("staff_add", "Может добавлять сотрудников"),
                    (
                        "hard_delete_and_recovery_products",
                        "Может окончательно удалять и восстанавливать товары",
                    ),
                ],
                "verbose_name": "разрешения сотрудников",
                "verbose_name_plural": "Разрешения сотрудников",
            },
        ),
    ]
