# Generated by Django 5.2.1 on 2026-01-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("view_dashboard", "Может просматривать статистику"),
                    ("can_change_product_price", "Может изменять цену товара"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                    ("can_change_order_status", "Может изменять статус заказа"),
                ],
            },
        ),
    ]
