# Generated by Django 5.2.1 on 2026-01-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpermission",
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("view_dashboard", "Может просматривать статистику"),
                    ("can_change_product_price", "Может изменять цену товара"),
                    ("can_manage_product_stock", "Может управлять остатками товара"),
                    ("can_change_order_status", "Может изменять статус заказа"),
                ],
                "verbose_name": "Разрешения сотрудника",
                "verbose_name_plural": "Разрешения сотрудников",
            },
        ),
    ]
