# Generated by Django 5.2.1 on 2026-01-29 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_alter_staffpermission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpermission",
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("view_dashboard", "Может просматривать статистику"),
                    ("add_staff", "Может добавлять сотрудников"),
                ],
                "verbose_name": "Разрешения сотрудника",
                "verbose_name_plural": "Разрешения сотрудников",
            },
        ),
    ]
