# Generated by Django 5.2.1 on 2026-01-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_staffpermission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpermission",
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("dashboard_view", "Может просматривать статистику"),
                    ("staff_add", "Может добавлять сотрудников"),
                ],
                "verbose_name": "разрешения сотрудников",
                "verbose_name_plural": "Разрешения сотрудников",
            },
        ),
    ]
