# Generated by Django 5.2.1 on 2026-04-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_staffpermission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpermission",
            options={
                "permissions": [
                    ("manage_permission", "Может управлять правами и группами"),
                    ("dashboard_view", "Может просматривать статистику"),
                    ("staff_add", "Может добавлять сотрудников"),
                    (
                        "hard_delete_and_recovery_products",
                        "Может окончательно удалять и восстанавливать товары",
                    ),
                ],
                "verbose_name": "разрешения сотрудников",
                "verbose_name_plural": "Разрешения сотрудников",
            },
        ),
    ]
